services:
  - type: web
    name: beereddy-agency-erp-backend
    env: node
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
