export const INDIAN_BANKS = [
  "State Bank of India (SBI)",
  "HDFC Bank",
  "ICICI Bank",
  "Punjab National Bank (PNB)",
  "Bank of Baroda (BOB)",
  "Axis Bank",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India (BOI)",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank (IOB)",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "YES Bank",
  "IDBI Bank",
  "Federal Bank",
  "IDFC FIRST Bank",
  "Bandhan Bank",
  "RBL Bank",
  "Karur Vysya Bank",
  "South Indian Bank",
  "City Union Bank",
  "Tamilnad Mercantile Bank",
  "Karnataka Bank",
  "DBS Bank India",
  "Standard Chartered Bank",
  "HSBC India",
  "Citibank India",
  "Telangana Grameena Bank (TGB)",
  "Andhra Pradesh Grameena Vikas Bank (APGVB)",
  "Andhra Pragathi Grameena Bank",
  "Airtel Payments Bank",
  "Paytm Payments Bank",
  "India Post Payments Bank (IPPB)",
  "Jio Payments Bank",
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Jana Small Finance Bank",
  "Capital Small Finance Bank",
  "ESAF Small Finance Bank",
  "Suryoday Small Finance Bank",
  "Utkarsh Small Finance Bank",
];
